#!/bin/bash

set -o errexit

set -o nounset

exec watchfiles celery.__main__.main \
    --args "-A authors_api.celery -b \"${CELERY_BROKER}\" flower --basic_auth=\"${CELERY_FLOWER_USE
    R}:${CELERY_FLOWER_PASSWORD}\""